# Generated by Django 5.2.14 on 2026-05-26 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_answer_media_mediatype_question_questiontype_round_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roundquestion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='roundquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='roundquestion',
            name='round',
        ),
        migrations.RemoveField(
            model_name='question',
            name='round',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.questiontype'),
        ),
        migrations.AlterField(
            model_name='round',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='api.game'),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='MediaType',
        ),
        migrations.DeleteModel(
            name='RoundQuestion',
        ),
        migrations.AddField(
            model_name='question',
            name='round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='api.round'),
            preserve_default=False,
        ),
    ]
