# Generated by Django 5.2.14 on 2026-05-26 10:35

from django.db import migrations

QUESTION_TYPES = [
    'Аукцион',
    'Ассоциация',
    'Варианты ответов',
    'Открытый вопрос',
]

def seed_question_types(apps, schema_editor):
    QuestionType = apps.get_model('api', 'QuestionType')
    for t in QUESTION_TYPES:
        QuestionType.objects.get_or_create(type=t)


def unseed_question_types(apps, schema_editor):
    QuestionType = apps.get_model('api', 'QuestionType')
    QuestionType.objects.filter(type__in=QUESTION_TYPES).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_question_question_type_alter_question_round'),
    ]

    operations = [
        migrations.RunPython(seed_question_types, unseed_question_types),
    ]
