# Generated by Django 5.2.13 on 2026-05-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
